# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_optimize_WH <- function(x, W, H, update_H, max_iter) {
    .Call(`_dtrans_rcpp_optimize_WH`, x, W, H, update_H, max_iter)
}

